apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart1.fullname" . }}
  labels:
    {{- include "chart1.labels" . | nindent 4 }}
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm